### Getting Player & Team Data

In [1]:
from nba_api.stats.static import players

In [6]:
# returns a list of dictionary of all players
players_dict = players.get_players()
len(players_dict)

4501

In [7]:
from nba_api.stats.static import teams
teams_dict = teams.get_teams()
len(teams_dict)

30

In [8]:
teams_dict

[{'id': 1610612737,
  'full_name': 'Atlanta Hawks',
  'abbreviation': 'ATL',
  'nickname': 'Hawks',
  'city': 'Atlanta',
  'state': 'Atlanta',
  'year_founded': 1949},
 {'id': 1610612738,
  'full_name': 'Boston Celtics',
  'abbreviation': 'BOS',
  'nickname': 'Celtics',
  'city': 'Boston',
  'state': 'Massachusetts',
  'year_founded': 1946},
 {'id': 1610612739,
  'full_name': 'Cleveland Cavaliers',
  'abbreviation': 'CLE',
  'nickname': 'Cavaliers',
  'city': 'Cleveland',
  'state': 'Ohio',
  'year_founded': 1970},
 {'id': 1610612740,
  'full_name': 'New Orleans Pelicans',
  'abbreviation': 'NOP',
  'nickname': 'Pelicans',
  'city': 'New Orleans',
  'state': 'Louisiana',
  'year_founded': 2002},
 {'id': 1610612741,
  'full_name': 'Chicago Bulls',
  'abbreviation': 'CHI',
  'nickname': 'Bulls',
  'city': 'Chicago',
  'state': 'Illinois',
  'year_founded': 1966},
 {'id': 1610612742,
  'full_name': 'Dallas Mavericks',
  'abbreviation': 'DAL',
  'nickname': 'Mavericks',
  'city': 'Dallas',
  'state': 'Texas',
  'year_founded': 1980},
 {'id': 1610612743,
  'full_name': 'Denver Nuggets',
  'abbreviation': 'DEN',
  'nickname': 'Nuggets',
  'city': 'Denver',
  'state': 'Colorado',
  'year_founded': 1976},
 {'id': 1610612744,
  'full_name': 'Golden State Warriors',
  'abbreviation': 'GSW',
  'nickname': 'Warriors',
  'city': 'Golden State',
  'state': 'California',
  'year_founded': 1946},
 {'id': 1610612745,
  'full_name': 'Houston Rockets',
  'abbreviation': 'HOU',
  'nickname': 'Rockets',
  'city': 'Houston',
  'state': 'Texas',
  'year_founded': 1967},
 {'id': 1610612746,
  'full_name': 'Los Angeles Clippers',
  'abbreviation': 'LAC',
  'nickname': 'Clippers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1970},
 {'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612748,
  'full_name': 'Miami Heat',
  'abbreviation': 'MIA',
  'nickname': 'Heat',
  'city': 'Miami',
  'state': 'Florida',
  'year_founded': 1988},
 {'id': 1610612749,
  'full_name': 'Milwaukee Bucks',
  'abbreviation': 'MIL',
  'nickname': 'Bucks',
  'city': 'Milwaukee',
  'state': 'Wisconsin',
  'year_founded': 1968},
 {'id': 1610612750,
  'full_name': 'Minnesota Timberwolves',
  'abbreviation': 'MIN',
  'nickname': 'Timberwolves',
  'city': 'Minnesota',
  'state': 'Minnesota',
  'year_founded': 1989},
 {'id': 1610612751,
  'full_name': 'Brooklyn Nets',
  'abbreviation': 'BKN',
  'nickname': 'Nets',
  'city': 'Brooklyn',
  'state': 'New York',
  'year_founded': 1976},
 {'id': 1610612752,
  'full_name': 'New York Knicks',
  'abbreviation': 'NYK',
  'nickname': 'Knicks',
  'city': 'New York',
  'state': 'New York',
  'year_founded': 1946},
 {'id': 1610612753,
  'full_name': 'Orlando Magic',
  'abbreviation': 'ORL',
  'nickname': 'Magic',
  'city': 'Orlando',
  'state': 'Florida',
  'year_founded': 1989},
 {'id': 1610612754,
  'full_name': 'Indiana Pacers',
  'abbreviation': 'IND',
  'nickname': 'Pacers',
  'city': 'Indiana',
  'state': 'Indiana',
  'year_founded': 1976},
 {'id': 1610612755,
  'full_name': 'Philadelphia 76ers',
  'abbreviation': 'PHI',
  'nickname': '76ers',
  'city': 'Philadelphia',
  'state': 'Pennsylvania',
  'year_founded': 1949},
 {'id': 1610612756,
  'full_name': 'Phoenix Suns',
  'abbreviation': 'PHX',
  'nickname': 'Suns',
  'city': 'Phoenix',
  'state': 'Arizona',
  'year_founded': 1968},
 {'id': 1610612757,
  'full_name': 'Portland Trail Blazers',
  'abbreviation': 'POR',
  'nickname': 'Trail Blazers',
  'city': 'Portland',
  'state': 'Oregon',
  'year_founded': 1970},
 {'id': 1610612758,
  'full_name': 'Sacramento Kings',
  'abbreviation': 'SAC',
  'nickname': 'Kings',
  'city': 'Sacramento',
  'state': 'California',
  'year_founded': 1948},
 {'id': 1610612759,
  'full_name': 'San Antonio Spurs',
  'abbreviation': 'SAS',
  'nickname': 'Spurs',
  'city': 'San Antonio',
  'state': 'Texas',
  'year_founded': 1976},
 {'id': 1610612760,
  'full_name': 'Oklahoma City Thunder',
  'abbreviation': 'OKC',
  'nickname': 'Thunder',
  'city': 'Oklahoma City',
  'state': 'Oklahoma',
  'year_founded': 1967},
 {'id': 1610612761,
  'full_name': 'Toronto Raptors',
  'abbreviation': 'TOR',
  'nickname': 'Raptors',
  'city': 'Toronto',
  'state': 'Ontario',
  'year_founded': 1995},
 {'id': 1610612762,
  'full_name': 'Utah Jazz',
  'abbreviation': 'UTA',
  'nickname': 'Jazz',
  'city': 'Utah',
  'state': 'Utah',
  'year_founded': 1974},
 {'id': 1610612763,
  'full_name': 'Memphis Grizzlies',
  'abbreviation': 'MEM',
  'nickname': 'Grizzlies',
  'city': 'Memphis',
  'state': 'Tennessee',
  'year_founded': 1995},
 {'id': 1610612764,
  'full_name': 'Washington Wizards',
  'abbreviation': 'WAS',
  'nickname': 'Wizards',
  'city': 'Washington',
  'state': 'District of Columbia',
  'year_founded': 1961},
 {'id': 1610612765,
  'full_name': 'Detroit Pistons',
  'abbreviation': 'DET',
  'nickname': 'Pistons',
  'city': 'Detroit',
  'state': 'Michigan',
  'year_founded': 1948},
 {'id': 1610612766,
  'full_name': 'Charlotte Hornets',
  'abbreviation': 'CHA',
  'nickname': 'Hornets',
  'city': 'Charlotte',
  'state': 'North Carolina',
  'year_founded': 1988}]

### Finding Games data

In [10]:
gsw_id = [team['id'] for team in teams_dict if team['abbreviation'] == 'GSW']
gsw_id[0]

1610612744

In [19]:
from nba_api.stats.endpoints import leaguegamefinder

game_finder = leaguegamefinder.LeagueGameFinder(team_id_nullable=gsw_id[0])
games = game_finder.get_data_frames()[0]

In [16]:
import pandas as pd
import numpy as np

In [17]:
pd.options.display.max_columns = 30

In [20]:
games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22020,1610612744,GSW,Golden State Warriors,0022000608,2021-03-15,GSW vs. LAL,L,240,97,34,79,0.430,13,37.0,0.351,16,24,0.667,9.0,21.0,30.0,24,9,2,22,23,-31.0
1,22020,1610612744,GSW,Golden State Warriors,0022000594,2021-03-14,GSW vs. UTA,W,241,131,50,89,0.562,16,31.0,0.516,15,18,0.833,5.0,35.0,40.0,33,12,2,13,26,12.0
2,22020,1610612744,GSW,Golden State Warriors,0022000576,2021-03-11,GSW @ LAC,L,240,104,38,88,0.432,9,36.0,0.250,19,27,0.704,5.0,39.0,44.0,20,6,6,16,23,-26.0
3,22020,1610612744,GSW,Golden State Warriors,0022000185,2021-03-04,GSW @ PHX,L,239,98,38,88,0.432,12,35.0,0.343,10,16,0.625,9.0,31.0,40.0,22,9,4,17,11,-22.0
4,22020,1610612744,GSW,Golden State Warriors,0022000550,2021-03-03,GSW @ POR,L,241,106,41,97,0.423,15,42.0,0.357,9,14,0.643,17.0,37.0,54.0,27,8,1,11,24,-2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3346,21983,1610612744,GOS,Golden State Warriors,0028300048,1983-11-05,GOS vs. NYK,W,240,102,35,92,0.380,0,1.0,0.000,32,45,0.711,25.0,18.0,43.0,20,16,4,17,27,NaN
3347,21983,1610612744,GOS,Golden State Warriors,0028300040,1983-11-03,GOS @ UTH,L,240,112,44,115,0.383,2,5.0,0.400,22,25,0.880,27.0,26.0,53.0,22,11,4,19,31,NaN
3348,21983,1610612744,GOS,Golden State Warriors,0028300029,1983-11-01,GOS @ KCK,L,240,114,42,91,0.462,0,2.0,0.000,30,40,0.750,12.0,18.0,30.0,29,15,3,16,28,NaN
3349,21983,1610612744,GOS,Golden State Warriors,0028300013,1983-10-29,GOS vs. POR,W,240,97,34,76,0.447,0,2.0,0.000,29,40,0.725,12.0,31.0,43.0,21,9,1,16,37,NaN
3350,21983,1610612744,GOS,Golden State Warriors,0028300004,1983-10-28,GOS @ SEA,W,240,110,42,89,0.472,0,0.0,NaN,26,37,0.703,21.0,26.0,47.0,26,11,2,19,34,NaN

In [23]:
games.groupby(games.SEASON_ID.str[-4:])[['GAME_ID']].count().loc['2015':]

           GAME_ID
SEASON_ID
2015           119
2016           112
2017           113
2018           117
2019            78
2020            43

In [27]:
games.loc[(games['SEASON_ID'].str[-4:] >= '2015')][['SEASON_ID', 'GAME_ID']].groupby(by='SEASON_ID').count()

           GAME_ID
SEASON_ID
12015            7
12016            7
12017            4
12018            5
12019            5
12020            3
22015           88
22016           88
22017           88
22018           90
22019           73
22020           40
42015           24
42016           17
42017           21
42018           22